# Generated by Django 5.0.6 on 2026-06-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_report_latitude_report_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='timeslot',
            new_name='slot',
        ),
    ]
