# Generated by Django 5.0.6 on 2026-06-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_rename_timeslot_checklistitem_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ đánh giá'), ('pass', 'Đạt'), ('fail', 'Không đạt')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
