# Generated by Django 5.0.6 on 2026-06-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_checklistitem_image_checklistitem_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='note',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='status',
        ),
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ đánh giá'), ('pass', 'Đạt'), ('fail', 'Không đạt')], default='pending', max_length=20),
        ),
    ]
