# Generated by Django 6.0.5 on 2026-06-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_remove_checklistitem_image_remove_checklistitem_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
