# Generated by Django 6.0.5 on 2026-06-09 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_auditissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='auditissue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditissue',
            name='note',
        ),
        migrations.RemoveField(
            model_name='auditissue',
            name='status',
        ),
        migrations.AddField(
            model_name='audit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditissue',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditissue',
            name='image',
            field=models.ImageField(upload_to='audit/'),
        ),
    ]
