# Generated by Django 6.0.5 on 2026-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_remove_audit_created_by_remove_auditissue_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditissue',
            name='title',
        ),
        migrations.AddField(
            model_name='auditissue',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
