# Generated by Django 6.0.5 on 2026-06-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0012_remove_auditissue_title_auditissue_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditissue',
            name='fix_image',
            field=models.ImageField(blank=True, null=True, upload_to='audit/fix/'),
        ),
        migrations.AddField(
            model_name='auditissue',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditissue',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('fixed', 'Đã khắc phục'), ('pass', 'Đạt'), ('fail', 'Không đạt')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='auditissue',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
