# Generated by Django 6.0.5 on 2026-06-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_auditissue_fix_image_auditissue_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditissue',
            name='fix_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='auditissue',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
