# Generated by Django 6.0.5 on 2026-06-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0014_alter_auditissue_fix_image_alter_auditissue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.checklistitem'),
        ),
    ]
