# Generated by Django 6.0.5 on 2026-06-14 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0015_alter_report_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.checklistitem'),
        ),
    ]
