# Generated by Django 6.0.5 on 2026-06-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0016_alter_report_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditissue',
            name='deduct_score',
            field=models.IntegerField(default=0),
        ),
    ]
