# Generated by Django 6.0.5 on 2026-06-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0018_auditfiximage_auditissueimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deduct_score', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
