# Generated by Django 6.0.5 on 2026-06-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0019_auditcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditcategory',
            old_name='deduct_score',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='auditissue',
            name='deduct_score',
        ),
        migrations.RemoveField(
            model_name='auditissue',
            name='fix_image',
        ),
        migrations.RemoveField(
            model_name='auditissue',
            name='image',
        ),
        migrations.RemoveField(
            model_name='auditissue',
            name='title',
        ),
        migrations.AlterField(
            model_name='audit',
            name='score',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='auditissue',
            name='status',
            field=models.CharField(choices=[('pass', 'Đạt'), ('fail', 'Không đạt'), ('pending', 'Chờ xử lý')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklist.auditcategory')),
            ],
        ),
        migrations.AddField(
            model_name='auditissue',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checklist.audititem'),
            preserve_default=False,
        ),
    ]
