# Generated by Django 6.0.5 on 2026-06-23 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0020_rename_deduct_score_auditcategory_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditissue',
            name='reviewed_at',
        ),
        migrations.AddField(
            model_name='auditissue',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.auditcategory'),
        ),
        migrations.AddField(
            model_name='auditissue',
            name='deduct_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditissue',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.audititem'),
        ),
        migrations.AlterField(
            model_name='auditissue',
            name='status',
            field=models.CharField(choices=[('pass', 'Đạt'), ('fail', 'Không đạt')], default='pass', max_length=20),
        ),
    ]
