# Generated by Django 6.0.5 on 2026-06-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0021_remove_auditissue_reviewed_at_auditissue_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditissue',
            name='status',
            field=models.CharField(choices=[('pass', 'Đạt'), ('fail', 'Không đạt'), ('fixed', 'Chờ QC duyệt')], default='pass', max_length=20),
        ),
    ]
