"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-p!knsj8esvrs67vmbts6*c(eva147mu-5!my!_=g^m(itq$q$)'

# SECURITY WARNING: don't run with debug turned on in production!
# Tui để True tạm thời nếu ông muốn test dưới Local, lên Render nhớ chỉnh biến môi trường nhé
DEBUG = os.environ.get('DEBUG', 'False') == 'True' if os.environ.get('CLOUDINARY_CLOUD_NAME') else True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # BẮT BUỘC: Cấu hình app Cloudinary storage nằm NGAY TRÊN staticfiles
    'cloudinary_storage',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Thêm app bổ trợ của Cloudinary
    'cloudinary',
    
    # App của ông
    'accounts',
    'checklist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database - TỰ ĐỘNG CHUYỂN ĐỔI LOCAL (SQLITE) VÀ PRODUCTION (POSTGRESQL)
if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.parse(os.environ.get("DATABASE_URL"))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ==============================================================================
# CLOUDINARY STORAGE CONFIGURATION (GÁN THẲNG - LỖI MẠNG LÀ PHẢI BÁO)
# ==============================================================================
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Ép Django sử dụng Cloudinary làm kho lưu trữ Media mặc định
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Cấu hình tài khoản lấy từ chính trang của ông
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dxeanigzh',
    'API_KEY': '936551848386457', 
    'API_SECRET': 'ÔNG_ĐIỀN_MÃ_API_SECRET_THẬT_CỦA_ÔNG', # Thay mã secret thật của ông vào đây
}

cloudinary.config(
    cloud_name = 'dxeanigzh',
    api_key = '936551848386457',
    api_secret = 'ÔNG_ĐIỀN_MÃ_API_SECRET_THẬT_CỦA_ÔNG', # Thay mã secret thật của ông vào đây
    secure = True
)

MEDIA_URL = "https://res.cloudinary.com/dxeanigzh/"

# Cấu hình ID mặc định giữ nguyên
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'